### PR TITLE
Add support for begin/end program and stop

### PR DESCRIPTION
**Pull request by Mitch9378**
Added support for highlighting 'begin-program' 'end-program'
 Added support for highlighting 'stop' and 'stop-quiet'
New snippets:
'begin-program ... end-program'

### CODE REVIEW

**Comment by Mitch9378** [comment]
I probably should have held off on updating the change log and version number. Let me know if you would like me to remove those.

**Comment by whanwells** [comment]
Please just remove the change to `package.json` since `apm` manages this automatically. Everything else looks good. Thanks!

**Comment by Mitch9378** [comment]
I have removed change to package.json.

Thanks

**Comment by whanwells** [comment]
Required further tweaks due to failing tests, but this was merged manually in v0.9.0. Thanks for the help, and sorry for the delay.

**Pull request closed without merging**
